# -*- coding: utf-8 -*-
"""Car_Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sQyM9niTfJa5Idge_XZllg0Zun0KPjsY
"""

# ----------------These code is to simulate a car game-----------

started=False  # This is to prevent repetitive start command


while True:  # If we write while True then the loop will run forever.

  command=input("what do you want? ").upper()

  if command=="HELP":
    print("""
    Start: Ready to start...
    Stop: Car stopped.
    quit: quit car. \n""")

  elif command=="START":

    if started:
      print("******* Car has already started *******\n")
    else:
      started= True
      print("Ready to start... \n")

  elif command=="STOP":

    if not started:
      print("******* Car has already stopped *******\n")
    else:
      started= False
      print("Car stopped!\n")

  elif command=="QUIT":
    print("Quit car\n")
    break
  else:
    print("******* Sorry, I don't understand it *******\n")

# ------------------ End of codes -----------------------------