# -*- coding: utf-8 -*-
"""Car_Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sQyM9niTfJa5Idge_XZllg0Zun0KPjsY
"""

# ----------------These code is to simulate a car game-----------

start_count=1  # This is to prevent repetitive start command
stop_count=1   # This is to prevent repetitive stop command


while True:  # If we write while True then the loop will run forever.

  command=input("what do you want? ").upper()

  if command=="HELP":
    print("""
    Start: Ready to start...
    Stop: Car stopped.
    quit: quit car. \n""")

  elif command=="START":
    if start_count<=1:
      print("Ready to start... \n")
      start_count+=1
    else:
      print("******* Car has already started *******\n")



  elif command=="STOP":
    if stop_count<=1:
      print("Car stopped!\n")
      stop_count+=1
    else:
      print("******* Car has already stopped *******\n")

  elif command=="QUIT":
    print("Quit car\n")
    break
  else:
    print("******* Sorry, I don't understand it *******\n")

# ------------------ End of codes -----------------------------