# -*- coding: utf-8 -*-
"""convert_weight.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHb-kSRyz8xAf4e45FfY4euwHFNz17jI
"""

# These codes are to convert your weight between pounds and kilogram
print("These codes are to convert your weight between pounds and kilogram\n")
weight=int(input('What is your weight: '))
weight_unit=input('weight unit(k: for kg or l: for pounds): ')
capital_weight_unit=weight_unit.upper()



if capital_weight_unit=="L":
  converted_weight=weight/2.20462
  converted_weight=round(converted_weight,2)
  print(f"your converted_weight is {converted_weight} kg")
else:
    converted_weight=weight*2.20462
    converted_weight=round(converted_weight,2)
    print(f"Your converted_weight is {converted_weight} pounds")

# ------------ End of the code----------------------------

