# -*- coding: utf-8 -*-
"""prices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hnfACw-yF7CIvYDQY1x6Umwd-JYjMbZ8
"""

#-------- These codes are to calculate the total price in shopping

import numpy as np
from math import *

items_count=int(input("items_count: ")) # The number of all items
item_number=np.zeros(items_count)
unit_prices=np.zeros(items_count)
total_prices=np.zeros(items_count)



for item in range(items_count):
  unit_prices[item]=int(input(f"enter the price of material number {item+1}: "))
  item_number[item]=int(input(f"enter the item number {item+1}:"))
  total_prices[item]=unit_prices[item]*item_number[item]


print(f" The list of total_prices is as {total_prices}")
sum=sum(total_prices)
print(f"The total price is {sum}")


#-------------- End of codes ----------------