# -*- coding: utf-8 -*-
"""sectret number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f6a1CAujYHbrJGB7W7v2e00xxawjEesv
"""

#---------------These codes are to find a sectret number -----------------------

secret_number=9
count_number=1
count_limitation=int(input('Enter the numbers of count_limitation: '))
print(f"You have {count_limitation} chances\n")


while count_number<=count_limitation:
  guess_number= int(input(f"guess_number {count_number}: "))

  if guess_number==secret_number:
    print('\n Result= ***** you won *****')
    break
  else:
    print("Result= wrong guess\n")
  count_number+=1
  if count_number>count_limitation:
    print('You missed your chances')
  else:
    print(f"You have {count_limitation+1-count_number} Chances")

#----------------------- End of the code  --------------------------------------